### ISSUE TITLE
Configure python logging to json

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-python-driver#111]
Python logging for batch jobs should also output json logging containing username and openEO batch job id.
Now it seems that we only see logs coming from log4j.

**Comment by soxofaan** [comment]
JSON style logging has now been implemented for
- flask context: request_id and user_id (when available) are added as fields
- batch job context: job_id and user_id are added as fields

**Comment by soxofaan** [comment]
In batch job logs there apparently some non-JSON left-overs:

warnings from python, e.g. 
```
    /opt/spark3_2_0/python/lib/pyspark.zip/pyspark/context.py:272: RuntimeWarning: Failed to add file [file:///opt/custom_processes.py] specified in 'spark.submit.pyFiles' to Python path:
       /data3/hadoop/yar...ss/filecache/64
       /data4/hadoop/ya...enss/appcache/application_1650104936572_43184/spark-2b7fbd19-3175-46e3-8249-f75a0a3f5a86/userFiles-b60f4b89-a6b9-41c3-9537-1a16d06312fc
```
```
/data1/hadoop/yarn/local/usercache/lippenss/appcache/application_1650104936572_43184/container_e5020_1650104936572_43184_01_000001/venv/lib/python3.8/site-packages/pyproj/crs/crs.py:280: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  projstring = _prepare_from_string(projparams)
```


exceptions in python threads:
```
    Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "/data1/hadoop/yar...ss/appcache/application_1650104936572_43184/container_e5020_1650104936572_43184_01_000001/venv/lib/python3.8/site-packages/spark_memlogger/memlogger.py", line 105, in _run
    self.log_mem(self.pid)
  File "/data1/hadoop/ya...ss/appcache/application_1650104936572_43184/container_e5020_1650104936572_43184_01_000001/venv/lib/python3.8/site-packages/spark_memlogger/memlogger.py", line 136, in log_mem
    rss_mem = parent.memory_info().rss
AttributeError: 'NoneType' object has no attribute 'memory_info'
````

this one comes from scala side I think:
```
    22/05/04 15:34:05 INFO layers.FileLayerProvider: Loading urn:eop:VITO:TERRASCOPE_S2_TOC_V2 with params DataCubeParameters(256, {}, FloatingLayoutScheme, ByDay, 8, None) and bands TOC-B01_60M;TOC-B02_10M;TOC-B03_10M;TOC-B04_10M;TOC-B05_20M;TOC-B06_20M;TOC-B07_20M;TOC-B08_10M;TOC-B8A_20M;TOC-B11_20M;TOC-B12_20M;SCENECLASSIFICATION_20M;RAA_60M;SZA_60M;VZA_60M
    ````

**Comment by soxofaan** [comment]
python warnings and threading exceptions should be covered now as well

**Comment by soxofaan** [comment]
Added support for logging unhandled exceptions
