### ISSUE TITLE
filter_bands wrong pushdown?

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-python-driver#154]
It seems that band filtering is pushed down beyond applying the UDF, which should not happen because the UDF is in fact using multiple bands.

https://discuss.eodc.eu/t/udf-output/504/3

```

Traceback (most recent call last):
  File "/opt/venv/lib64/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/venv/lib64/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/users/auth.py", line 88, in decorated
    return f(*args, **kwargs)
  File "/opt/venv/lib64/python3.8/site-packages/openeo_driver/views.py", line 809, in queue_job
    backend_implementation.batch_jobs.start_job(job_id=job_id, user=user)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 1122, in start_job
    self._start_job(job_id, user.user_id, _get_vault_token)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 1152, in _start_job
    and self._scheduled_sentinelhub_batch_processes(spec['process_graph'], api_version, registry,
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 1469, in _scheduled_sentinelhub_batch_processes
    metadata = metadata.filter_bands(band_names)
  File "/opt/venv/lib64/python3.8/site-packages/openeo/metadata.py", line 370, in filter_bands
    return self._clone_and_update(dimensions=[
  File "/opt/venv/lib64/python3.8/site-packages/openeo/metadata.py", line 371, in <listcomp>
    d.filter_bands(band_names) if isinstance(d, BandDimension) else d
  File "/opt/venv/lib64/python3.8/site-packages/openeo/metadata.py", line 149, in filter_bands
    bands=[self.bands[self.band_index(b)] for b in bands]
  File "/opt/venv/lib64/python3.8/site-packages/openeo/metadata.py", line 149, in <listcomp>
    bands=[self.bands[self.band_index(b)] for b in bands]
  File "/opt/venv/lib64/python3.8/site-packages/openeo/metadata.py", line 124, in band_index
    raise ValueError("Invalid band name/index {b!r}. Valid names: {n!r}".format(b=band, n=band_names))
ValueError: Invalid band name/index 'B02'. Valid names: ['DEM']
```

**Comment by jdries** [comment]
https://github.com/Open-EO/openeo-python-driver/commit/19be86ac35c76e644a6b206bce6ed4813cae21fd
