### ISSUE TITLE
Do real basic auth

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-driver#186]
with #168  we now have a basic config system that also can hold some secrets like real basic auth (instead of the silly basic implementation we have now)

**Comment by soxofaan** [comment]
Another possibility: do basic auth through OIDC password grant behind the scenes (for example using VITO keycloak for the Terrascope back-end). This would allow to use standard tools (Keycloak) to create/manage users, instead of a DIY solution through config

**Comment by soxofaan** [comment]
:(  now the tests for this new feature fail on jenkins

```
    def test_ephemeral_fileserver_subprocess(tmp_path):
        (tmp_path / "hello.txt").write_text("Hello world!")
        (tmp_path / "get.py").write_text(
            textwrap.dedent(
                """
                import sys
                import requests
                resp = requests.get(sys.argv[1])
                print(f"{resp.status_code} {resp.text!r}")
              """
            )
        )
        with ephemeral_fileserver(path=tmp_path) as root_url:
            cmd = [sys.executable, str(tmp_path / "get.py"), f"{root_url}/hello.txt"]
            res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
>           assert (res.returncode, res.stdout, res.stderr) == (0, b"200 'Hello world!'\n", b"")
E           assert (0, b"200 'He...le ignored\n') == (0, b"200 'He...rld!'\n", b'')
E             At index 2 diff: b'Error processing line 1 of /usr/local/lib/python3.8/site-packages/distutils-precedence.pth:\n\n  Traceback (most recent call last):\n    File "/usr/lib64/python3.8/site.py", line 169, in addpackage\n      exec(line)\n    File "<string>", line 1, in <module>\n  AttributeError: module \'_distutils_hack\' has no attribute \'ensure_shim\'\n\nRemainder of file ignored\n' != b''
E             Full diff:
E               (
E                0,
E                b"200 'Hello world!'\n",
E             -  b'',
E             +  b'Error processing line 1 of /usr/local/lib/python3.8/site-packages/distutils-'
E             +  b'precedence.pth:\n\n  Traceback (most recent call last):\n    File "/usr/lib'
E             +  b'64/python3.8/site.py", line 169, in addpackage\n      exec(line)\n    File'
E             +  b' "<string>", line 1, in <module>\n  AttributeError: module \'_distutils_ha'
E             +  b"ck' has no attribute 'ensure_shim'\n\nRemainder of file ignored\n",
E               )

tests/test_testing.py:210: AssertionError
```

found this related issue about this: https://github.com/pypa/setuptools/issues/2983


Apparently our jenkins pipeline pin down setuptools to pretty old version
```
pip install -I --upgrade pip setuptools==54.1.3 wheel==0.37.1
```
(`setuptools==54.1.3` is from March 2021)

**Comment by soxofaan** [comment]
FYI, basic auth is not practically non-functional on terrascope backend as it raises a "unsufficient credits" error

```
curl -i -X POST -H 'Content-Type: application/json' -H 'Authorization: Bearer basic//abc123==' --data '{"process":{"process_graph":{}}}' https://openeo-dev.vito.be/openeo/1.1/result

HTTP/2 401 
content-type: application/json
date: Wed, 25 Oct 2023 13:35:13 GMT
content-length: 188
strict-transport-security: max-age=31536000; includeSubDomains

{"message":"You do not have sufficient credits to perform this request. Please visit https://portal.terrascope.be/pages/pricing to find more information on how to buy additional credits."}

```
