### ISSUE TITLE
weird errors when expanding test coverage for `openeo_driver.utils.logging`

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-driver#230]
While working on logging tweaks for https://github.com/Open-EO/openeo-aggregator/issues/74 I expanded  `openeo_driver.utils.logging` feature set a bit and improved related test coverage.

On jenkins, some  tests in https://github.com/Open-EO/openeo-python-driver/blob/master/tests/util/test_logging.py (using the pytester fixture) started to fail because of weird warning (?) in the output of some test scripts:

```
Error processing line 1 of
/usr/local/lib/python3.8/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'ensure_shim'

Remainder of file ignored
```

**Comment by soxofaan** [comment]
we already had that problem in #193 apparently 

problem is discussed at https://github.com/pypa/setuptools/issues/2983  and https://github.com/pypa/setuptools/issues/2957

upgrading setuptools in the jenkins setup to a recent enough version is probably going to take some time, so it's probably best, to just ignore these warnings for now

**Comment by soxofaan** [comment]
internal ref: GDD-2879
