### ISSUE TITLE
Better handling of HTTP issues/timeouts when resolving OIDC access tokens

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-driver#96]
Issue raised in openEO Platform forums:

> 0:01:01 Job ‘vito-ec7c5c49-a54f-4221-b659-e3e18ecb1fbd’: queued (progress N/A)
> 0:01:11 Job ‘vito-ec7c5c49-a54f-4221-b659-e3e18ecb1fbd’: queued (progress N/A)
> 0:01:24 Job ‘vito-ec7c5c49-a54f-4221-b659-e3e18ecb1fbd’: queued (progress N/A)
> OpenEoApiError: [500] unknown: [403] TokenInvalid: Authorization token has expired or is invalid. Please authenticate again.

in application logs I found around time of that job:

> [2021-11-11 16:55:37,660] 9 WARNING in openeo_driver.users.auth: Failed to resolve OIDC access token
> ...
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='aai.egi.eu', port=443): Max retries exceeded with url: /oidc/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90df136910>: Failed to establish a new connection: [Errno 110] Connection timed out'))

If aai.egi.eu is (partially) down, resolving the access token fails

what could be improved:
- openeo-python-driver: at least make error clearer that the problem is with the identity provider,  not the access token itself
- openeo-python-driver: add a bit of retry logic to cover temporary glitches
- openeo-python-client: don't stop the batch job status poll loop when such a temp glitch happens

**Comment by soxofaan** [comment]
full stack trace

```
[2021-11-11 16:55:37,660] 9 WARNING in openeo_driver.users.auth: Failed to resolve OIDC access token
Traceback (most recent call last):
  File "/home/openeo/venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/openeo/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/openeo/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/openeo/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/openeo/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/openeo/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/openeo/venv/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/home/openeo/venv/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f90df136910>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/openeo/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/openeo/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/openeo/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='aai.egi.eu', port=443): Max retries exceeded with url: /oidc/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90df136910>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/openeo/venv/lib/python3.8/site-packages/openeo_driver/users/auth.py", line 176, in resolve_oidc_access_token
    userinfo_url = self._get_userinfo_endpoint(oidc_provider=oidc_provider)
  File "/home/openeo/venv/lib/python3.8/site-packages/openeo_driver/users/auth.py", line 168, in _get_userinfo_endpoint
    resp = requests.get(oidc_provider.discovery_url)
  File "/home/openeo/venv/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/openeo/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/openeo/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/openeo/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/openeo/venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='aai.egi.eu', port=443): Max retries exceeded with url: /oidc/.well-known/openid-configuration (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f90df136910>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

**Comment by soxofaan** [comment]
>  1.  openeo-python-driver: at least make error clearer that the problem is with the identity provider, not the access token itself
>  2.  openeo-python-driver: add a bit of retry logic to cover temporary glitches
>  3.  openeo-python-client: don't stop the batch job status poll loop when such a temp glitch happens

1 and 3 are implemented now.
I'm not sure it is still necessary to address 2 for a couple of reasons:
- if there is an availability issue, it's not the best idea to add more requests
- you typically want to wait a bit between requests, but it's also not a good idea do that kind of sleeping server side: it's better to have a quick response and address errors client side.

The combination of 1 and 3 should be good enough for now I think.

Will close this for now, but feel free to reopen if 2 still should be done
